apiVersion: v1
kind: Namespace
metadata:
  name: openshift-performance-addon-operator
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-performance-addon-operator
  namespace: openshift-performance-addon-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  channel: "4.10" 
  name: performance-addon-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace

# https://docs.openshift.com/container-platform/4.10/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html

---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: systemreservedset
  annotations:
    kubeletconfig.experimental: |
      {"allowedUnsafeSysctls":["net.core.somaxconn"]}
spec:
  cpu:     
    reserved: 0-3,56-59
    isolated: 4-7
  memory: "16Gi"
  nodeSelector:
    node-role.kubernetes.io/master: ""



