apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-secret
  namespace: kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  kafka-secret.sh: |
    #!/bin/bash -e


    # Extract CA cert
    oc -n kafka-cluster get secret mgnt-kafka-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/ca-bundle.crt
    echo "ca-bundle.crt Job finished"
    # Extract client key
    oc -n kafka-cluster get secret mgnt-kafka-clients-ca -o jsonpath='{.data.ca\.key}' | base64 -d > /tmp/tls.key
    echo "tls.key Job finished"
    # Extract client certificate
    oc -n kafka-cluster get secret mgnt-kafka-clients-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/tls.crt
    echo "tls.crt Job finished"
