apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: systemreservedset
  annotations:
    kubeletconfig.experimental: |
      {"allowedUnsafeSysctls":["net.core.somaxconn"]}
spec:
  cpu:     
    reserved: 0-3,56-59
    isolated: 4-7
  memory: "16Gi"
  nodeSelector:
    node-role.kubernetes.io/master: ""


